# Generated by Django 6.0.4 on 2026-05-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pedido_fecha_pedido_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
